py_binary(
    name = 'app',
    srcs = ['app.py'],
    deps = ['//demo/third_party:marisa_trie',
            '//demo/third_party:ipdb'],
)

py_binary(
    name = 'bundle_app',
    srcs = ['bundle_app.py'],
    deps = ['//demo/third_party:external']
)


